service: lambda-tutorial
configValidationMode: warn

custom:
  profile:
    dev: "suite-dev"
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: python3.7
  profile: ${self:custom.profile.${opt:stage}}
  region: ${opt:region}
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonSQSFullAccess
    - arn:aws:iam::aws:policy/AWSLambda_FullAccess
    - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
    - arn:aws:iam::aws:policy/AmazonS3FullAccess
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "*"
  tags:
    sls-framework: true

functions:
  hello-handler:
    handler: src.handler.hello
    memorySize: 1024

package:
  exclude:
    - "node_modules/**"
    - "venv/**"

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-step-functions
